### ISSUE TITLE
Specify a digest

### ISSUE THREAD

**Issue by blackwood** [exos/genpasswd#1]
Heads up that `genpasswd -d` throws a warning on node v6:

```
(node:4258) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest.
```

...and errors out for the same reason on node v8:

```
    throw new TypeError(
    ^

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2 (crypto.js:623:10)
    at Object.generateDeterministic (/usr/local/lib/node_modules/genpasswd/lib/password.js:211:12)
```

**Comment by exos** [comment]
Fix in release v0.2.3
https://github.com/exos/genpasswd/releases/tag/v0.2.3

Thanks you @blackwood
